name: Deploy NGINX to OKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and push Docker image
    #   run: |
    #     docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:latest .
    #     docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest

    - name: Install Python 3 and OCI CLI dependencies
      run: sudo apt-get update && sudo apt-get install -y python3 python3-pip zip

    - name: Install OCI CLI
      run: |
        bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" -- --accept-all-defaults

    - name: Verify OCI CLI installation
      run: /home/runner/bin/oci --version
      
    

    - name: Set up OCI config directory
      run: |
        mkdir -p ~/.oci
        echo "${{ secrets.OCI_CLI_CONFIG_FILE }}" > ~/.oci/config
        echo "${{ secrets.OCI_CLI_KEY_FILE }}" > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem

    - name: Install kubectl
      run: |
            sudo rm /etc/apt/sources.list.d/kubernetes.list
            sudo apt-get update
            echo "deb https://apt.kubernetes.io/ kubernetes main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
            sudo apt-get update
            sudo apt-get install -y kubectl
            # sudo apt-get update && sudo apt-get install -y apt-transport-https
            # curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            # echo "deb https://apt.kubernetes.io/ kubernetes main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
            # sudo apt-get update
            # sudo apt-get install -y kubectl
        
    - name: Create .kube directory
      run: mkdir -p /home/runner/.kube

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config
    - name: print config
      run: cat ~/.kube/config
    - name: Verify kubectl configuration
      run: kubectl get all
      
    - name: Verify kubectl configuration
      run: kubectl cluster-info dump

    - name: Deploy to OKE
      run: |
        kubectl apply -f deployment.yml
